version: '3.8'
services:
  app:
    build: .
    container_name: finsage-app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL=postgresql+asyncpg://postgres:postgres@db:5432/finsage
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4jpassword
      - JWT_SECRET=supersecret
      - GEMINI_API_KEY=dummy-key
      - GEMINI_API_URL=https://gemini.googleapis.com/v1/generate
    depends_on:
      - db
      - milvus
      - neo4j
  db:
    image: postgres:15
    container_name: finsage-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finsage
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  milvus:
    image: milvusdb/milvus:v2.3.9
    container_name: finsage-milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    depends_on:
      - etcd
      - minio
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: finsage-etcd
    environment:
      - ETCD_UNSUPPORTED_ARCH=arm64
    ports:
      - "2379:2379"
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: finsage-minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data
  neo4j:
    image: neo4j:5.19
    container_name: finsage-neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4jdata:/data
volumes:
  pgdata:
  miniodata:
  neo4jdata:
